name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Stage new config and deploy
        env:
          SPLUNK_PASS: ${{ secrets.SPLUNK_PASS }}
        run: |
          sudo -u root /bin/bash -c "cd $GITHUB_WORKSPACE && ./link_new_apps.sh"
          sudo -u splunk /opt/splunk/bin/splunk reload deploy-server -auth admin:$SPLUNK_PASS
